config/routes.rb
Rails.application.routes.draw do
  #legacy
  get '/dev',   to: redirect("/course")
  get '/web',   to: redirect("/course")
  get '/method',  to: redirect("/course")
  get '/teachers',to: redirect("/course#teachers")
  get '/sponsoring',to: redirect("/sponsor_diversity")
  get '/marketingjob',   to: redirect("/")

  namespace :admin do
    resources :users
    resources :courses
    resources :resumes
    resources :applies

    root to: "users#index"
  end

  devise_for :users, controllers: { registrations: "registrations" }

  resource  :resume , except: [:destroy , :new , :edit] do
    get :progress, on: :member
  end
  get :application , to: "applies#show"
  post :application , to: "applies#create"
  post :cancel_application , to: "applies#cancel"


  root to: 'high_voltage/pages#show' , id: 'index'

  get "/blog" , to: "blog#index" , as: :blog_index
  get "/blog/*title" , to: "blog#page" , as: :blog_page
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :user

  default_scope {order('created_at DESC') }

  def percent
    attribs = percent_attributes
    non_nil = attribs.sum{ |name| self.attributes[name].blank? ? 0 : 1}
    (non_nil * 100) / attribs.length
  end

  def percent_attributes
    Resume.column_names - ["id" , "user_id" , "created_at", "updated_at"]
  end
end

app/controllers/admin/resumes_controller.rb
module Admin
  class ResumesController < AdminController
    def index
      @q = Resume.search params[:q]
      @resume_scope = @q.result(:distinct => true)
      @resumes = @resume_scope.page( params[:page] )
    end

    def show
      @resume = Resume.find(params[:id])
    end
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_resume, only: [:show, :update , :progress ]

  def show
  end

  def progress
    render layout: false
  end

  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = current_user.resume
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:user_id , :finance ,
                                     :school, :uni, :internship, :work, :tech_skills,
                                     :soft_skills, :projects, :other, :interests, :motivation)
    end
end

app/helpers/resumes_helper.rb
module ResumesHelper


  # define a bunch of defaults for the best_in_place call
  def resume_in_place field , attributes = {}
    txt = I18n.t("resumes.#{field}")
    button = @resume.send(field).blank? ? "Ok" : "Edit"
    br = proc {|txtt| raw(txtt.to_s.gsub("\n" , "<br>")) }
    defaults = { :url => resume_path , place_holder: txt , display_with: br}
    unless [:street , :city , :country].include? field
      defaults.merge! ok_button: button,  ok_button_class: "btn btn-success" ,
                      cancel_button: "Cancel" , cancel_button_class:  "btn btn-warning",
                      inner_class:  "form-control" , as: :textarea ,
                      sanitize: false , html_attrs: {rows: 10}
    end
    attributes.reverse_merge! defaults
    best_in_place(@resume , field , attributes)
  end

end

app/views/admin/resumes/index.html.haml
.row.resumes_index_start
  .col-md-9.resumes
    .row
      .col-md-10
        %h2= @resume_scope.length.to_s + " Resumes"
        =paginate @resumes
  .col-md-3
.row
  .col-md-9
    %div
      %table.table.table-striped.table-bordered.table-condensed
        %thead
          %tr
            %th=sort_link [:admin,@q], :user_name
            %th Percent
            %th=sort_link [:admin,@q], :updated_at
        %tbody
          - @resumes.each do |resume|
            %tr{:class => "line-#{cycle("1","2")}"}
              %td= link_to resume.user.name , admin_user_path(resume.user)
              %td= link_to "#{resume.percent} %"  , admin_resume_path(resume), :title => "Show"
              %td= resume.updated_at.to_date
    =paginate @resumes
  .col-md-3
    = search_form_for [:admin , @q], :html => { :class => "form-horizontal" }, :method => :get do |f|
      .form-group
        = f.text_field :user_name_cont , :class => "form-control" , :placeholder =>  "User"
      = f.submit "Filter",  :id => :filter , :class => "btn btn-success"
      = link_to  "Cancel", admin_resumes_path, :class => "btn btn-warning"
.resumes_index_end

app/views/admin/resumes/show.html.haml
%h2
  = "Resume : "
  = link_to @resume.user.name , admin_user_path(@resume.user)
  = "#{@resume.percent} %"

%h4
  -if app = @resume.user.application
    = link_to "Applied" , admin_applies_path(app)
    for
    = link_to app.primary_choice_course.name , admin_course_path(app.primary_choice_course)
    on
    = app.created_at.to_date
  -else
    Not applied

- @resume.percent_attributes.each do |name |
  %p
    %b= "#{name} : "
    = @resume.send(name).to_s

= link_to "Back", admin_resumes_path, :class => "btn btn-warning"