config/routes.rb
Rails.application.routes.draw do
  #legacy
  get '/dev',   to: redirect("/course")
  get '/web',   to: redirect("/course")
  get '/method',  to: redirect("/course")
  get '/teachers',to: redirect("/course#teachers")
  get '/sponsoring',to: redirect("/sponsor_diversity")
  get '/marketingjob',   to: redirect("/")

  namespace :admin do
    resources :users
    resources :courses
    resources :resumes
    resources :applies

    root to: "users#index"
  end

  devise_for :users, controllers: { registrations: "registrations" }

  resource  :resume , except: [:destroy , :new , :edit] do
    get :progress, on: :member
  end
  get :application , to: "applies#show"
  post :application , to: "applies#create"
  post :cancel_application , to: "applies#cancel"


  root to: 'high_voltage/pages#show' , id: 'index'

  get "/blog" , to: "blog#index" , as: :blog_index
  get "/blog/*title" , to: "blog#page" , as: :blog_page
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates_presence_of :street
  validates_presence_of :city
  validates_presence_of :country

  has_one :application , dependent: :destroy , class_name: :Apply
  has_one :resume      , dependent: :destroy

  enum role: [:user, :teacher, :admin]

  after_initialize :set_default_role, :if => :new_record?

  default_scope {order('created_at DESC') }

  def set_default_role
    self.role ||= :user
  end

  def resume
    Resume.find_or_create_by( :user_id => self.id)
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController

    def index
      @q = User.search( params[:q])
      @user_scope = @q.result(:distinct => true).includes(:application, :resume)
      @users = @user_scope.page( params[:page] )
    end

    def show
      @user = User.find(params[:id])
    end

  end
end

app/helpers/admin/users_helper.rb
module Admin
  module UsersHelper

    def application_link(user)
      return "" unless user.application
      link_to user.application.primary_choice_course.start_date ,
                admin_apply_path(user.application) ,
                title:  user.application.summary
    end
  end
end

app/views/admin/users/index.html.haml
.row.users_index_start
  .col-md-9.users
    .row
      .col-md-10
        %h2= @user_scope.length.to_s + " Users"

        =paginate @users
  .col-md-3
    = #image_tag "users.jpg" , :class => "img-responsive"
.row
  .col-md-9
    %div
      %table.table.table-striped.table-bordered.table-condensed
        %thead
          %tr
            %th=sort_link @q, :email
            %th Resume
            %th Application
            %th=sort_link @q, :confirmed_at
            %th=sort_link @q, :sign_in_count
        %tbody
          - @users.each do |user|
            %tr{:class => "line-#{cycle("1","2")}"}
              %td= link_to user.email , admin_user_path(user), :title => "#{user.street}\n#{user.city}\n#{user.country}"
              %td= link_to "#{user.resume.percent} %" , admin_resume_path(user.resume)
              %td= application_link(user)
              %td= user.confirmed_at ? time_ago_in_words(user.confirmed_at) : ""
              %td= user.sign_in_count.to_s
    =paginate @users
  .col-md-3
    = search_form_for [:admin , @q], :html => { :class => "form-horizontal" }, :method => :get do |f|
      .form-group
        = f.text_field :email_cont , :class => "form-control" , :placeholder =>  "Email"
      .form-group
        = f.text_field :street_cont ,:class => "form-control" , :placeholder =>  "Street"
      = f.submit "Filter",  :id => :filter , :class => "btn btn-success"
      = link_to  "Cancel", admin_users_path, :class => "btn btn-warning"
.users_index_end

app/views/admin/users/show.html.haml
%h2
  = @user.name
  \:
  = @user.email
  -if @user.admin?
    (Admin)
%h4
  = "Resume : "
  = link_to "#{@user.resume.percent} %" , admin_resume_path(@user.resume)

%h4
  -if app = @user.application
    = link_to "Applied" , admin_applies_path(app)
    for
    = link_to app.primary_choice_course.name , admin_course_path(app.primary_choice_course)
    on
    = app.created_at.to_date
  -else
    Not applied

%p
  %b= "Last sign : " + @user.last_sign_in_at.to_s
%p
  %b= "Sign in count : " + @user.sign_in_count.to_s
%p
  %b= "Name : " + @user.name.to_s
%p
  %b= "Street : " + @user.street.to_s
%p
  %b= "City : " + @user.city.to_s
%p
  %b= "Country : " + @user.country.to_s

= link_to "Back", admin_users_path, :class => "btn btn-warning"