config/routes.rb
Rails.application.routes.draw do
  #legacy
  get '/dev',   to: redirect("/course")
  get '/web',   to: redirect("/course")
  get '/method',  to: redirect("/course")
  get '/teachers',to: redirect("/course#teachers")
  get '/sponsoring',to: redirect("/sponsor_diversity")
  get '/marketingjob',   to: redirect("/")

  namespace :admin do
    resources :users
    resources :courses
    resources :resumes
    resources :applies

    root to: "users#index"
  end

  devise_for :users, controllers: { registrations: "registrations" }

  resource  :resume , except: [:destroy , :new , :edit] do
    get :progress, on: :member
  end
  get :application , to: "applies#show"
  post :application , to: "applies#create"
  post :cancel_application , to: "applies#cancel"


  root to: 'high_voltage/pages#show' , id: 'index'

  get "/blog" , to: "blog#index" , as: :blog_index
  get "/blog/*title" , to: "blog#page" , as: :blog_page
end

app/controllers/admin/courses_controller.rb
module Admin
  class CoursesController < AdminController

    before_action :load_course, :only => [:show, :edit, :update, :destroy]

    def index
      @q = Course.search(params[:q])
      @course_scope = @q.result(:distinct => true)
      @courses = @course_scope.page( params[:page] )
    end

    def show
    end

    def new
      @course = Course.new
      render :edit
    end

    def edit
    end

    def create
      @course = Course.create(params_for_course)
      if @course.save
        redirect_to admin_course_path(@course), :notice => "Course created"
      else
        render :edit
      end
    end

    def update
      @course.update_attributes params_for_course
      if @course.save
        redirect_to admin_course_path(@course), :notice => "Course updated"
      else
        render :action => :edit
      end
    end

    def destroy
      #    @course.deleted_at = Time.now
      redirect_to admin_courses_url
    end

    private

    def load_course
      @course = Course.find(params[:id])
    end

    def params_for_course
      params.require(:course).permit!
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/admin/courses/edit.html.haml
%h2.courses_edit_start
  = params["action"].upcase
  Course
= simple_form_for([:admin , @course]) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :extra
    = f.input :start

  .form-actions
    = f.button :submit
    = link_to "Back", admin_courses_path, :class => "btn btn-warning"

app/views/admin/courses/index.html.haml
.row.courses_index_start
  .col-md-9.courses
    .row
      .col-md-8
        %h2 Courses
        =paginate @courses
      .col-md-2
        = link_to  "New course" , new_admin_course_path , :class => "btn btn-primary"
      .col-md-2
  .col-md-3

.row
  .col-md-9
    %div
      %table.table.table-striped.table-bordered.table-condensed
        %thead
          %tr
            %th=sort_link [:admin,@q],  :name
            %th Applications
            %th Extra
            %th Start
            %th{:colspan => "2"}
              %label.checkbox
                = @course_scope.length.to_s + " Courses"
        %tbody
          - @courses.each do |course|
            %tr{:class => "line-#{cycle("1","2")}"}
              %td.name=course.name
              %td=link_to course.applications.count.to_s , admin_course_applicants_path(course)
              %td=course.extra
              %td=course.start
              %td= link_to "Show" , admin_course_path(course), :title => "Show"
              %td= link_to "Edit" , edit_admin_course_path(course), :title => "Edit"
    =paginate @courses
  .col-md-3
    = search_form_for [:admin,@q], :html => { :class => "form-horizontal" }, :method => :get do |f|
      .form-group
        = f.text_field :name_cont , :class => "form-control", :placeholder =>  "Name"
      = f.submit "Filter", :id => :filter , :class => "btn btn-success"
      = link_to  "Cancel", admin_courses_path, :class => "btn btn-warning"
.courses_index_end

app/views/admin/courses/show.html.haml
%h2
  Course :
  = @course.name

%h4
  =link_to "#{@course.applications.count} Applicants" , admin_course_applicants_path(@course)


.col-md-12
  %p
    %b
      = "Name: " +  @course.name.to_s
  %p
    %b
      = "Extra : " +  @course.extra.to_s
  %p
    %b
      = "Start : " + @course.start.to_s

= link_to "Edit", edit_admin_course_path(@course), :class => "btn btn-success"
= link_to "Back", admin_courses_path, :class => "btn btn-warning"