config/routes.rb
Rails.application.routes.draw do
  #legacy
  get '/dev',   to: redirect("/course")
  get '/web',   to: redirect("/course")
  get '/method',  to: redirect("/course")
  get '/teachers',to: redirect("/course#teachers")
  get '/sponsoring',to: redirect("/sponsor_diversity")
  get '/marketingjob',   to: redirect("/")

  namespace :admin do
    resources :users
    resources :courses
    resources :resumes
    resources :applies

    root to: "users#index"
  end

  devise_for :users, controllers: { registrations: "registrations" }

  resource  :resume , except: [:destroy , :new , :edit] do
    get :progress, on: :member
  end
  get :application , to: "applies#show"
  post :application , to: "applies#create"
  post :cancel_application , to: "applies#cancel"


  root to: 'high_voltage/pages#show' , id: 'index'

  get "/blog" , to: "blog#index" , as: :blog_index
  get "/blog/*title" , to: "blog#page" , as: :blog_page
end

app/views/layouts/_footer.html.haml
.dark_footer
  .footer_container
    .address_col
      = image_tag "logos/web_logo_mobile.png" , :class => "footer-logo"
      %p.slogan Live in bootcamp, learn the code
      %address
        %table
          %tbody
            %tr
              %td
                %i.fa.icon-location
                %br/
                %br/
                %br/
              %td
                Isokiskontie 6
                %br/
                10470 Fiskars
                %br/
                Finland
            %tr
              %td
                %i.fa.icon-phone
              %td Phone: +358-40 7308052
            %tr
              %td
                %i.fa.icon-mail
              %td
                %a{:href => "mailto:info@webdev.camp"} info@webdev.camp
    .links_l
      %h6.letter-spacing-1 RESOURCES
      %ul.footer-links.list-unstyled
        %li.icon-angle-right= link_to "Teachers" , page_path(:course , anchor: :teachers)
        %li.icon-angle-right= link_to "Payment Plans" , page_path(:payment)
        %li.icon-angle-right= link_to "Application Process", page_path(:apply)
        %li.icon-angle-right= link_to "Prepare yourself", page_path(:prepare)
        %li.icon-angle-right= ext_link "Beginners guide", "https://medium.com/webdev-camp/tagged/basics"
      %h6.letter-spacing-1 JOBS
      %ul.footer-links.list-unstyled
        %li.icon-angle-right= link_to "Teaching" , page_path(:teaching)
        //%li.icon-angle-right= link_to "Marketing" , page_path(:marketingjob)

    .links_r
      %h6.letter-spacing-1= link_to "BLOG" , blog_index_url
      - Page.pages.values[0 .. 2].each do |page|
        %ul.footer-links.list-unstyled
          %li.icon-angle-right= link_to page.title , blog_page_url(page.slug)
      %h6.letter-spacing-1 OPPORTUNITIES
      %ul.footer-links.list-unstyled
        %li.icon-angle-right= link_to "For Companies" , page_path(:for_companies)
        %li.icon-angle-right= link_to "Sponsor diversity" , page_path(:sponsor_diversity)
        %li.icon-angle-right= link_to "Diversity scholarships" , page_path(:diversity_scholarships)

    .footer-sign
      %h5.letter-spacing-1 Account
      %ul.footer-links.list-unstyled
        -if user_signed_in?
          %li= sign_out_link
          %li= link_to "Your Account" ,  edit_user_registration_path
          %li= link_to "Resume" ,   resume_path
        -else
          %li
            = simple_form_for(:user, :url => session_url(:user), :html => { :role => 'form' , class: "form-horizontal"}) do |f|
              .input-group
                %span.input-group-addon
                  %i.fa.icon-mail
                = f.email_field :email, class: 'form-control' , placeholder: :email
              .input-group
                %span.input-group-addon
                  %i.fa.icon-lock
                = f.password_field :password, class: 'form-control' , placeholder: :password
              .input-group-btn
                = f.submit "Sign in" , class: "btn btn-success btn-block"


      .margin-top-20
        =social_link("https://www.facebook.com/webdev.camp", "facebook") do
          %i.icon-facebook
        =social_link("https://twitter.com/webdev_camp", "twitter") do
          %i.icon-twitter
        =social_link("https://www.instagram.com/webdev.camp", "instagram") do
          %i.icon-instagram
        = social_link( "https://medium.com/webdev-camp" , "medium" ) do
          =image_tag "logos/medium.png"
  .container-fluid
    .row.copyright
      .col-md-7
        © All Rights Reserved, Web Dev Camp, a subsidiary of Lightning Raisa & Torsten Oy
      .col-md-5.text-sm-right
        %ul.nomargin.list-inline.mobile-block
          %li.list-inline-item
            =link_to "Terms & Conditions" , page_path(:terms)
          %li.list-inline-item •
          %li.list-inline-item
            =link_to "Privacy" , page_path(:privacy)
          -if user_signed_in?
            %li.list-inline-item •
            %li.list-inline-item
              =link_to "House Rules" , page_path(:rules)

- if Rails.env.production?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    var the_id = 'UA-76401513-1';
    ga('create', the_id.replace("-1" , "-3") , 'auto');
    ga('send', 'pageview');

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "flash alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
    .message{id:  "flash_#{name}"}= msg

app/views/layouts/_navigation.html.haml
%nav.navbar.fixed-top.navbar-toggleable-sm.navbar-light
  %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarNav",
                                              "aria-expanded" => "false",
                                              "aria-label" => "Toggle navigation",
                                              "data-target" => "#navbarResponsive",
                                              "data-toggle" => "collapse",
                                              :type => "button"}
    %span.navbar-toggler-icon
  #navbarResponsive.collapse.navbar-collapse
    %a.navbar-brand{:href => page_path(:index) }
      = image_tag "logos/web_logo.png" , class: :desktop
      = image_tag "logos/web_logo_mobile.png" , class: :mobile
    %ul.navbar-nav.ml-auto
      - { "Course" => page_path(:course) , "Camp" => page_path(:camp)  ,
        "Q & A" => page_path(:answers) }.each do | menu, slug|
        %li.nav-item{class: (request.path == slug) && "active" }
          =link_to menu , slug ,class: "nav-link"
      -unless user_signed_in?
        %li.nav-item
          = link_to "Closed" ,  page_path(:apply) , class: "nav-link"
        %li.nav-item
          = link_to "|" ,  page_path(:apply) , class: "nav-link"
      -if user_signed_in?
        %li.nav-item= link_to "|" ,  edit_user_registration_path , class: "nav-link"
        - { "Profile" => edit_user_registration_path , "Resume" => resume_path  ,
          "Application" => application_path }.each do | menu, slug|
          %li.nav-item.nav-small{class: (request.path == slug) && "active" }
            =link_to menu , slug ,class: "nav-link"
        %li.nav-item.nav-small= sign_out_link  class: "nav-link"
      -unless user_signed_in?
        %li.nav-item.nav-small= link_to "Sign in" , new_user_session_path, class: "nav-link"

app/views/layouts/_slidetop.haml
/ SLIDE TOP
#slidetop.bg-finland
  .container
    .row
      .col-sm-4
        %h4
          %i.icon-heart
          WHY Web Dev Camp?
        %p
          More than just a place to learn a new skill, Web Dev Camp is a an
          %b
            experience.
          %br
          Going from a regular computer user to creating your own apps is awesome in itself.
          But having personal guidance, learning in motivated small groups and a living in
          the restoring wonder that is nature make it an experience you’re not likely to forget
          in your lifetime.
      .col-sm-4
        %h4
          %i.icon-question
          QUESTIONS?
        We tried to describe what to expect as best we can. Still, people understand in different
        ways, so if you have any questions don't hesitate to contact us.
        %ul.list-unstyled
          %li
            %a{:href => "mailto:info@webdev.camp"}
              %i.fa.icon-angle-right
              %b Email:
              info@webdev.camp
          %li
            = ext_link "https://gitter.im/rubyclerks/office_clerk" do
              %i.fa.icon-angle-right
              %b Gitter chat:
              web_dev_camp/info
          %li
            %i.fa.icon-angle-right
              %b Phone:
              +358 (0)40 730 80 52
      .col-sm-4
        %h4
          %i.icon-envelope
          WERE WE ARE?
        %ul.list-unstyled
          %li
            Fiskarsintie 513
            %br
            10480 Antskog
            %br
            Finland
          %li
            -if user_signed_in?
              %li= sign_out_link
              %li= link_to "Account" ,  edit_user_registration_path
            -else
              %li
                = simple_form_for(:user, :url => session_path(:user), :html => { :role => 'form' , class: "form-horizontal"}) do |f|
                  .input-group
                    %span.input-group-addon
                      %i.fa.icon-mail
                    = f.email_field :email, class: 'form-control' , placeholder: :email
                  .input-group
                    %span.input-group-addon
                      %i.fa.icon-lock
                    = f.password_field :password, class: 'form-control' , placeholder: :password
                    %span.input-group-btn
                      = f.submit "Sign in" , class: "btn btn-success"
  %a.slidetop-toggle{:href => "#"}

app/views/layouts/_submenu.html.haml
#page-menu.page-menu-color
  .container
    %nav.pull-right
      %button#page-menu-mobile.fa.icon-menu
      %ul.list-inline
        - { "method" => "Method" , "web" => "Web" , "dev" => "Dev" , "teachers" => "Teachers" }.each do |slug , menu|
          %li{class: (params[:id] == slug) && "active" }
            =link_to menu , page_path(slug)

app/views/layouts/admin.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title= content_for?(:title) ? content_for(:title) :  "Admin"
    = stylesheet_link_tag "admin" ,  :media => :all
    = #javascript_include_tag "admin"
    = csrf_meta_tags
  %body{:style => ""}
    .container-fluid
      = render "layouts/admin/admin_menu"
      = render "layouts/admin/messages"

      = yield

      .row
        .col-md-12
          %br

app/views/layouts/application.html.haml
!!!
/[if IE 8] <html class="ie ie8">
/[if IE 9] <html class="ie ie9">
/ [if gt IE 9]><!
%html
  / <![endif]
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    / mobile settings
    %meta{:content => "width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0", :name => "viewport"}/
    %title= @title || "Web Dev Camp"
    %meta{:content => "web development course, web dev course", :name => "keywords"}/
    %meta{:content => "#{description}", :name => "description"}/
    %meta{:content => "Torsten Ruger", :name => "Author"}/
    %meta{ name: "google-site-verification" , content: "U86xRj-I-z08iE7t1EOXwZeiVLj9ItO3ydSpqrsdE3Y"}

    / Google Tag Manager
    :javascript
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-THCLJTM');
    / End Google Tag Manager

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    - if Rails.env.production?
      :javascript
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','https://connect.facebook.net/en_US/fbevents.js');
        var fb_id = 953870144744;
        fbq('init', fb_id + '750');
        fbq('track', 'PageView');
  %body
    / Google Tag Manager (noscript)
    %noscript
      %iframe{:height => "0", :src => "https://www.googletagmanager.com/ns.html?id=GTM-THCLJTM", :style => "display:none;visibility:hidden", :width => "0"}

    .header
      = render 'layouts/navigation'
      = render 'layouts/messages'
    .main
      = yield
    = render 'layouts/footer'
    %a#toTop{:href => "#"}
    - if Rails.env.production?
      :javascript
        window.__lo_site_id = 59342;
        	(function() {
        		var wa = document.createElement('script'); wa.type = 'text/javascript'; wa.async = true;
        		wa.src = 'https://d10lpsik1i8c69.cloudfront.net/w.js';
        		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(wa, s);
        	  })();